package it.droidcon.androidstudioplugin.livetemplates;

import com.intellij.codeInsight.template.impl.DefaultLiveTemplatesProvider;
import org.jetbrains.annotations.Nullable;

/**
 * @author Adam Szewera
 * This class implements the DefaultLiveTemplatesProvider interface and
 * makes it possible to add to the IDE the Live Templates specified in the liveTemplates/Synesthesia.xml
 * file under the resources directory.
 * The file Synesthesia.xml was generated by IntelliJ by using the Live Templates sections of settings and
 * than copyting the ~/.Idea<version>/config/templates/Synesthesia.xml here into the specific plugin directory.
 *
 * Live templates let you insert frequently-used or custom code constructs
 * into your source code file quickly, efficiently, and accurately.
 */
public class DroidconLiveTemplateProvider implements DefaultLiveTemplatesProvider {

    @Override
    public String[] getDefaultLiveTemplateFiles() {
        return new String[] {"liveTemplates/MyLiveTemplates"};
    }

    @Nullable
    @Override
    public String[] getHiddenLiveTemplateFiles() {
        return new String[0];
    }

}
